psw/psw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usr.urls'))
]

psw/usr/urls.py
from django.urls import path
from usr import views
app_name='usr'
urlpatterns = [
    path('', views.index, name='index'),
    path('other', views.other, name='other'),
    path('register', views.register, name='register'),
    path('login',views.user_login, name='user_login'),
    path('logout',views.user_logout, name='logout'),
    path('special',views.special, name='special')

]

psw/usr/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

psw/usr/forms.py
from django import forms
from django.contrib.auth.models import User
from usr.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

psw/usr/views.py
from django.shortcuts import render
from usr.forms import UserForm,UserProfileInfoForm


# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, response
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'usr/index.html')

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect('other')


# Create your views here.
def index(request):
    return render(request,'usr/index.html')

def other(request):
    return render(request,'usr/other.html')

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
                profile.save()
                registered = True
        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'usr/register.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect('other')
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'usr/login.html')

psw/templates/usr/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

      <a class="navbar-brand" href="{% url 'usr:index' %}">HOME</a>
      <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
      <a class="nav-item nav-link" href="{% url 'usr:register' %}">Register</a>
      <a class="nav-item nav-link" href="{% url 'usr:other' %}">other</a>

      {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'usr:logout' %}">Logout</a>
      {% else %}
        <a class="nav-item nav-link" href="{% url 'usr:user_login' %}">Login</a>

      {% endif%}
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>


  </body>
</html>

psw/templates/usr/index.html
<!DOCTYPE html>
{% extends 'usr/base.html'%}
{% block body_block %}
<div class="jumbotron">
  <h1>HOMEEEEEEEEEEEE</h1>
</div>



{% endblock %}

psw/templates/usr/login.html
{% extends 'usr/base.html'%}
{% block body_block %}

<div class="jumbotron">
  <h1>login</h1>
  <form method="post" action="{% url 'usr:user_login' %}" >
    {% csrf_token %}
    <label for="username">username</label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password">Password</label>
    <input type="password" name="password">
    <input type="submit" name="" value="submit">
  </form>
</div>


{% endblock %}

psw/templates/usr/other.html
<!DOCTYPE html>
{% extends 'usr/base.html'%}
{% block body_block %}
<div class="jumbotron">
  <h1>otherrrrrrrrrrrrr</h1>
  <h2>otttttttttttttttt</h2>
</div>
{% endblock %}

psw/templates/usr/register.html
<!DOCTYPE html>
{% extends 'usr/base.html'%}
{% load static %}
{% block body_block %}

<div class="jumbotron">
{% if registered %}
  <h1>thankyou for Registering</h1>
  {% else %}
  <h1>register here</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p}}
    {{ profile_form.as_p }}
    <input type="submit" value="Register">
  </form>
{% endif %}

</div>

{% endblock %}